### ISSUE TITLE
This site does not work

### ISSUE THREAD

**Issue by dariodip** [antonioaltamura/antonioaltamura.github.io#1]
Please check out your website, it seems not to be working.

**Comment by antonioaltamura** [comment]
I haven't pushed my site yet. When it'll work you will notice for sure.

**Comment by antonioaltamura** [comment]
I choose when this issue have to be closed. Thank you for your understanding.

**Comment by dariodip** [comment]
My issue, my rules

**Comment by antonioaltamura** [comment]
I'm sorry, you must to be new here. My repo, my rules.

**Comment by dariodip** [comment]
Go to close your own issues 😃

**Comment by antonioaltamura** [comment]
I reported you to GitHub platform team. If you find yourself unable to commit on your repositories don't worry, it what a report meant to be.

**Comment by dariodip** [comment]
You were wrong! I did many commits on my repos, also on my website (that works perfectly). Perhaps you don't know what is a report 😃

**Comment by dariodip** [comment]
Hi! This site still does not work. Can I help you?

**Comment by antonioaltamura** [comment]
It looks like you never had the experience, some of us used to work.

**Comment by antonioaltamura** [comment]
perfection needs time.

**Comment by dariodip** [comment]
This site still does not work
