### ISSUE TITLE
This site still does not work

### ISSUE THREAD

**Issue by dariodip** [antonioaltamura/antonioaltamura.github.io#3]
This site still does not work

_Originally posted by @dariodip in https://github.com/antonioaltamura/antonioaltamura.github.io/issues/1#issuecomment-500336845_

**Comment by antonioaltamura** [comment]
Then I'm pretty sure it's a PEBKAC case. Thanks.

**Comment by dariodip** [comment]
Ok, now it works but it still sucks

**Comment by antonioaltamura** [comment]
That's because you project yourself into things, so you're unable to see beauty.

**Comment by dariodip** [comment]
I can't understand the background pic you choose.

![Schermata 2019-06-25 alle 10 36 33](https://user-images.githubusercontent.com/9026586/60082986-2ddc8b80-9735-11e9-936e-2bb2e10877ec.png)
